services:
  postgres:
    image: postgres:16
    container_name: rentcar-postgres
    environment:
      POSTGRES_DB: rentcar
      POSTGRES_USER: rentcar
      POSTGRES_PASSWORD: rentcar
    ports:
      - "5432:5432"
    volumes:
      - rentcar_postgres_data:/var/lib/postgresql/data

volumes:
  rentcar_postgres_data: