ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_address VARCHAR(500);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_place_id VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS dropoff_address VARCHAR(500);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS dropoff_place_id VARCHAR(255);
