server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentcar
    username: rentcar
    password: rentcar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

rentcar:
  admin:
    username: admin
    password: change-me

app:
  public-base-url: http://localhost:8091
